-- movie
DROP TABLE IF EXISTS `MOVIE_LIST` RESTRICT;

-- movie
CREATE TABLE `MOVIE_LIST` (
`MOVIE_ID` INT UNSIGNED NOT NULL COMMENT '영화Id', -- 영화Id
`TITLE` VARCHAR(500) NULL COMMENT '제목', -- 제목
`IMG_TITLE` VARCHAR(500) NULL COMMENT '이미지 이름' -- 이미지 이름
)
COMMENT 'movie';

-- movie
ALTER TABLE `MOVIE_LIST`
ADD CONSTRAINT `PK_MOVIE_LIST` -- movie 기본키
PRIMARY KEY (
`MOVIE_ID` -- 영화Id
);

ALTER TABLE `MOVIE_LIST`
MODIFY COLUMN `MOVIE_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '영화Id';

-- sample data
INSERT INTO MOVIE_LIST VALUES(1, '타이타닉','titanic.jpg');
INSERT INTO MOVIE_LIST VALUES(2, '토이스토리','toystory.jpg');

INSERT INTO MOVIE_LIST VALUES(3, '뮬란','mulan.jpg');
INSERT INTO MOVIE_LIST VALUES(4, '쿵푸팬더','kungfupanda.jpg');